# Generated by Django 5.2.1 on 2025-06-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Manufatto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "stato",
                    models.CharField(
                        choices=[
                            ("PROGRAMMATO", "PROGRAMMATO"),
                            ("IN CORSO", "IN CORSO"),
                            ("COMPLETATO", "COMPLETATO"),
                        ],
                        max_length=50,
                    ),
                ),
                ("data_creazione", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
