# Generated by Django 6.0.2 on 2026-03-11 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufatto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('stato', models.CharField(choices=[('IN ESERCIZIO', 'IN ESERCIZIO'), ('PROGRAMMATO', 'PROGRAMMATO')], default='IN ESERCIZIO', max_length=50)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('comune', models.CharField(blank=True, max_length=100, null=True)),
                ('localita', models.CharField(blank=True, max_length=100, null=True)),
                ('ubicazione', models.CharField(blank=True, max_length=255, null=True)),
                ('depuratore_associato', models.CharField(blank=True, max_length=255, null=True)),
                ('recapito_emissario', models.CharField(blank=True, max_length=255, null=True)),
                ('tipologia_sfioratore', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['comune', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='info_idriche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ae_civ', models.FloatField(blank=True, null=True, verbose_name='AE CIV')),
                ('ae_ind', models.FloatField(blank=True, null=True, verbose_name='AE IND')),
                ('ae_tot', models.FloatField(blank=True, null=True, verbose_name='AE TOT')),
                ('q_civ', models.FloatField(blank=True, null=True, verbose_name='Q CIV')),
                ('q_ind', models.FloatField(blank=True, null=True, verbose_name='Q IND')),
                ('qnm', models.FloatField(blank=True, null=True, verbose_name='Qnm')),
                ('qs', models.FloatField(blank=True, null=True, verbose_name='Qs')),
                ('pavv', models.FloatField(blank=True, null=True, verbose_name='Pavv')),
                ('qs_qnm_ratio', models.CharField(blank=True, max_length=50, null=True)),
                ('qs_gt_pavv', models.CharField(blank=True, max_length=100, null=True)),
                ('qs_pavv_ratio', models.CharField(blank=True, max_length=50, null=True)),
                ('tipologia_sfioro_rr6', models.CharField(blank=True, max_length=50, null=True)),
                ('e_conforme', models.CharField(blank=True, max_length=50, null=True)),
                ('vasca_reg_regionale', models.CharField(blank=True, max_length=100, null=True)),
                ('bacino_proprio_ha', models.FloatField(blank=True, null=True)),
                ('q_meteo_ingresso_ls', models.FloatField(blank=True, null=True)),
                ('q_limite_ingresso_ls', models.FloatField(blank=True, null=True)),
                ('portata_specifica_scarico', models.FloatField(blank=True, null=True)),
                ('ha_imp', models.FloatField(blank=True, null=True)),
                ('qscolmata_ls', models.FloatField(blank=True, null=True)),
                ('vasca_ptua', models.CharField(blank=True, max_length=100, null=True)),
                ('scadenza_autorizzazione', models.CharField(blank=True, max_length=100, null=True)),
                ('atto_provincia_n', models.CharField(blank=True, max_length=100, null=True)),
                ('consorzio_competente', models.CharField(blank=True, max_length=255, null=True)),
                ('scadenza_concessione', models.CharField(blank=True, max_length=100, null=True)),
                ('atto_consorzio_n', models.CharField(blank=True, max_length=100, null=True)),
                ('note_autorizzazioni', models.TextField(blank=True, null=True)),
                ('codice_provincia_manufatto', models.CharField(blank=True, max_length=100, null=True)),
                ('codice_provincia_scarico', models.CharField(blank=True, max_length=100, null=True)),
                ('bacino_maggiore_10000', models.CharField(blank=True, max_length=10, null=True)),
                ('qs_maggiore_20', models.CharField(blank=True, max_length=10, null=True)),
                ('scarica_lago_suolo', models.CharField(blank=True, max_length=100, null=True)),
                ('manufatto_limitante', models.CharField(blank=True, max_length=255, null=True)),
                ('manufatto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info_idriche', to='manufatti.manufatto')),
            ],
        ),
        migrations.CreateModel(
            name='info_geografiche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitudine', models.FloatField(blank=True, null=True)),
                ('longitudine', models.FloatField(blank=True, null=True)),
                ('manufatto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info_geografiche', to='manufatti.manufatto')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='documenti/%Y/%m/%d/')),
                ('data_caricamento', models.DateTimeField(auto_now_add=True)),
                ('manufatto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documenti', to='manufatti.manufatto')),
            ],
        ),
    ]
