# Generated by Django 5.2.1 on 2025-06-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manufatti", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="manufatto",
            name="info_geografiche",
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name="manufatto",
            name="info_idriche",
            field=models.CharField(blank=True),
        ),
    ]
