# Generated by Django 6.0.2 on 2026-03-11 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufatti', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info_idriche',
            name='manufatto_limitante',
        ),
    ]
