# Generated by Django 5.2.1 on 2025-06-24 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manufatti", "0002_manufatto_info_geografiche_manufatto_info_idriche"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="manufatto",
            name="info_geografiche",
        ),
        migrations.RemoveField(
            model_name="manufatto",
            name="info_idriche",
        ),
        migrations.CreateModel(
            name="info_geografiche",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitudine", models.FloatField(blank=True, null=True)),
                ("longitudine", models.FloatField(blank=True, null=True)),
                (
                    "manufatto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="info_grografiche",
                        to="manufatti.manufatto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="info_idriche",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("portata", models.FloatField(blank=True, null=True)),
                ("pressione", models.FloatField(blank=True, null=True)),
                (
                    "manufatto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="info_idriche",
                        to="manufatti.manufatto",
                    ),
                ),
            ],
        ),
    ]
