# Generated by Django 6.0.2 on 2026-03-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufatti', '0002_remove_info_idriche_manufatto_limitante'),
    ]

    operations = [
        migrations.AddField(
            model_name='info_idriche',
            name='manufatto_limitante',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
