# Generated by Django 5.2.1 on 2026-03-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufatti', '0003_info_idriche_manufatto_limitante'),
    ]

    operations = [
        migrations.AddField(
            model_name='info_idriche',
            name='sistema_rilevamento',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Sistema Rilevamento'),
        ),
    ]
