# Generated by Django 5.2.1 on 2025-07-03 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manufatti", "0003_remove_manufatto_info_geografiche_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="info_geografiche",
            name="manufatto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="info_geografiche",
                to="manufatti.manufatto",
            ),
        ),
    ]
