# Generated by Django 5.2.1 on 2026-03-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufatti', '0004_info_idriche_sistema_rilevamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufatto',
            name='stato',
            field=models.CharField(choices=[('IN ESERCIZIO', 'IN ESERCIZIO'), ('DISMESSO', 'DISMESSO')], default='IN ESERCIZIO', max_length=50),
        ),
    ]
