# Generated by Django 5.2.1 on 2025-07-23 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manufatti", "0004_alter_info_geografiche_manufatto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Intervento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descrizione", models.TextField(blank=True)),
                ("data", models.DateField()),
                (
                    "manufatto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interventi",
                        to="manufatti.manufatto",
                    ),
                ),
            ],
        ),
    ]
