# Generated by Django 5.2.1 on 2026-03-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufatti', '0005_alter_manufatto_stato'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufatto',
            name='alert_messaggio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
