# Generated by Django 5.2.1 on 2025-08-17 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufatti', '0005_intervento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Intervento',
        ),
    ]
