# Generated by Django 4.2.23 on 2025-09-17 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufatti', '0006_delete_intervento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='documenti/%Y/%m/%d/')),
                ('data_caricamento', models.DateTimeField(auto_now_add=True)),
                ('manufatto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documenti', to='manufatti.manufatto')),
            ],
        ),
    ]
