# Generated by Django 4.2.23 on 2025-09-17 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufatti', '0007_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='manufatto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documenti', to='manufatti.manufatto'),
        ),
    ]
