# Generated by Django 4.2.23 on 2025-11-03 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufatti', '0008_alter_documento_manufatto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info_idriche',
            name='portata',
        ),
        migrations.RemoveField(
            model_name='info_idriche',
            name='pressione',
        ),
        migrations.AddField(
            model_name='info_idriche',
            name='ae_civ',
            field=models.FloatField(blank=True, null=True, verbose_name='AE CIV'),
        ),
        migrations.AddField(
            model_name='info_idriche',
            name='ae_ind',
            field=models.FloatField(blank=True, null=True, verbose_name='AE IND'),
        ),
        migrations.AddField(
            model_name='info_idriche',
            name='ae_tot',
            field=models.FloatField(blank=True, null=True, verbose_name='AE TOT'),
        ),
        migrations.AddField(
            model_name='info_idriche',
            name='bacino_proprio_ha',
            field=models.FloatField(blank=True, null=True, verbose_name='Bacino proprio (ha)'),
        ),
        migrations.AddField(
            model_name='info_idriche',
            name='e_conforme',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='è conforme?'),
        ),
        migrations.AddField(
            model_name='info_idriche',
            name='ha_imp',
            field=models.FloatField(blank=True, null=True, verbose_name='ha imp'),
        ),
        migrations.AddField(
            model_name='info_idriche',
            name='manufatto_limitante',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Manufatto limitante'),
        ),
        migrations.AddField(
            model_name='info_idriche',
            name='pavv',
            field=models.FloatField(blank=True, null=True, verbose_name='Pavv'),
        ),
        migrations.AddField(
            model_name='info_idriche',
            name='portata_specifica_scarico',
            field=models.FloatField(blank=True, null=True, verbose_name='Portata specifica allo scarico [l/s haimp]'),
        ),
        migrations.AddField(
            model_name='info_idriche',
            name='q_civ',
            field=models.FloatField(blank=True, null=True, verbose_name='Q CIV'),
        ),
        migrations.AddField(
            model_name='info_idriche',
            name='q_ind',
            field=models.FloatField(blank=True, null=True, verbose_name='Q IND'),
        ),
        migrations.AddField(
            model_name='info_idriche',
            name='q_limite_ingresso_ls',
            field=models.FloatField(blank=True, null=True, verbose_name='Q limite ingresso al manufatto (l/s)'),
        ),
        migrations.AddField(
            model_name='info_idriche',
            name='q_meteo_ingresso_ls',
            field=models.FloatField(blank=True, null=True, verbose_name='Q meteo in ingresso al manufatto (l/s)'),
        ),
        migrations.AddField(
            model_name='info_idriche',
            name='qnm',
            field=models.FloatField(blank=True, null=True, verbose_name='Qnm'),
        ),
        migrations.AddField(
            model_name='info_idriche',
            name='qs',
            field=models.FloatField(blank=True, null=True, verbose_name='Qs'),
        ),
        migrations.AddField(
            model_name='info_idriche',
            name='qs_gt_pavv',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Qs > Pavv'),
        ),
        migrations.AddField(
            model_name='info_idriche',
            name='qs_pavv_ratio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Qs/Pavv'),
        ),
        migrations.AddField(
            model_name='info_idriche',
            name='qs_qnm_ratio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Qs/Qnm'),
        ),
        migrations.AddField(
            model_name='info_idriche',
            name='qscolmata_ls',
            field=models.FloatField(blank=True, null=True, verbose_name='Qscolmata l/s'),
        ),
        migrations.AddField(
            model_name='info_idriche',
            name='tipologia_sfioro_rr6',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='TIPOLOGIA'),
        ),
        migrations.AddField(
            model_name='info_idriche',
            name='vasca_reg_regionale',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vasca Reg. Regionale'),
        ),
        migrations.AddField(
            model_name='manufatto',
            name='comune',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='manufatto',
            name='depuratore_associato',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='manufatto',
            name='localita',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='manufatto',
            name='recapito_emissario',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='manufatto',
            name='tipologia_sfioratore',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='manufatto',
            name='ubicazione',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='info_geografiche',
            name='manufatto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info_geografiche', to='manufatti.manufatto'),
        ),
        migrations.AlterField(
            model_name='info_idriche',
            name='manufatto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info_idriche', to='manufatti.manufatto'),
        ),
    ]
