# Generated by Django 4.2.23 on 2025-11-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufatti', '0009_remove_info_idriche_portata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='info_idriche',
            name='atto_consorzio_n',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Atto Consorzio n°'),
        ),
        migrations.AddField(
            model_name='info_idriche',
            name='atto_provincia_n',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Atto Provincia n°'),
        ),
        migrations.AddField(
            model_name='info_idriche',
            name='consorzio_competente',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Consorzio competente'),
        ),
        migrations.AddField(
            model_name='info_idriche',
            name='note_autorizzazioni',
            field=models.TextField(blank=True, null=True, verbose_name='Note Autorizzazioni /Concessioni'),
        ),
        migrations.AddField(
            model_name='info_idriche',
            name='scadenza_autorizzazione',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Scadenza autorizzazione Provincia'),
        ),
        migrations.AddField(
            model_name='info_idriche',
            name='scadenza_concessione',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Scadenza concessione Consorzio'),
        ),
        migrations.AddField(
            model_name='info_idriche',
            name='vasca_ptua',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vasca PTUA'),
        ),
    ]
