# Generated by Django 6.0.2 on 2026-02-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufatti', '0010_info_idriche_atto_consorzio_n_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufatto',
            name='stato',
            field=models.CharField(choices=[('PROGRAMMATO', 'PROGRAMMATO'), ('IN ESECUZIONE', 'IN ESECUZIONE')], default='IN ESECUZIONE', max_length=50),
        ),
    ]
